
branches:
  only:
    - master

language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24

env:
   - TEST_DIR=HelloMapAndroid
   - TEST_DIR=AdvancedMapAndroid
   - TEST_DIR=CartoMapAndroid

before_install:
   - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null

script: cd $TEST_DIR && ./gradlew build connectedCheck
