
branches:
  only:
    - master

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - build-tools-24.0.2
    - android-24

env:
   - TEST_DIR=HelloMapAndroid
   - TEST_DIR=AdvancedMapAndroid
   - TEST_DIR=CartoMapAndroid

script: cd $TEST_DIR && ./gradlew build connectedCheck
